# Generated by Django 4.2.11 on 2024-05-09 22:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', max_length=200, verbose_name='Имя')),
                ('last_name', models.CharField(default='', max_length=200, verbose_name='Фамилия')),
                ('email', models.CharField(max_length=254, verbose_name='Почта')),
            ],
            options={
                'verbose_name': 'Покупатель',
                'verbose_name_plural': 'Покупатели',
            },
        ),
        migrations.CreateModel(
            name='Concerts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200, verbose_name='Название концерта')),
                ('date_concert', models.DateTimeField(verbose_name='Дата проведения')),
                ('place', models.CharField(default='', max_length=200, verbose_name='Место проведения')),
                ('singer', models.CharField(default='', max_length=200, verbose_name='Певец')),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(choices=[('fun-zone', 'Фан-Зона'), ('dance-floor', 'Танцпол'), ('M-G', 'Встреча с певцом')], max_length=50, verbose_name='Тип билета')),
                ('cost', models.IntegerField(verbose_name='Цена билета')),
            ],
            options={
                'verbose_name': 'Место',
                'verbose_name_plural': 'Места',
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buy_date', models.DateTimeField(verbose_name='Дата покупки билета')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Music.buyer', verbose_name='Покупатель')),
                ('concert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Music.concerts', verbose_name='Концерт')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Music.place', verbose_name='Место')),
            ],
            options={
                'verbose_name': 'Покупка',
                'verbose_name_plural': 'Покупки',
            },
        ),
    ]
