# Generated by Django 4.2.11 on 2024-05-09 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Music', '0002_rename_concerts_concert'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservation',
            options={'verbose_name': 'Покупка билета', 'verbose_name_plural': 'Покупки билетов'},
        ),
    ]
