# Generated by Django 4.2.11 on 2024-05-09 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Music', '0003_alter_reservation_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='concert',
            options={'verbose_name': 'Место', 'verbose_name_plural': 'Места'},
        ),
    ]
