# Generated by Django 4.2.11 on 2024-05-09 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Music', '0004_alter_concert_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reservation',
            new_name='Buying',
        ),
    ]
