# Generated by Django 4.2.11 on 2024-05-09 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Music', '0005_rename_reservation_buying'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='concert',
            options={'verbose_name': 'Концерт', 'verbose_name_plural': 'Концерты'},
        ),
    ]
